#!/usr/bin/env bash
# Configures an Ubuntu server so that localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
